buttons_size: 32
additional_html: ''
additional_css: "img {\r\n  background-image: var(--icon-share-primary);\r\n  background-image: url(data:image/svg+xml;charset=utf-8,%3Csvg width='30' height='30' viewBox='0 0…0.253c0-1.51-1.236-2.769-2.745-2.769z' fill='%23FFF'/%3E%3C/g%3E%3C/svg%3E);\r\n  width: 30px !important;\r\n  height: 30px !important;\r\n}"
additional_js: "a2a_config.onclick = 1;\r\na2a_config.prioritize = [\"twitter\", \"facebook\", \"linkedin\", \"googleplus\", \"whatsapp\", \"email\"];\r\na2a_config.num_services = 6;\r\na2a_config.icon_color = \"#007c75\";\r\na2a_config.color_main = \"#007c75\";\r\n// a2a_config.color_border = \"#dddddd\";\r\na2a_config.color_link_text = \"#007c75\";\r\na2a_config.color_link_text_hover = \"#005e59\";\r\n"
universal_button: custom
custom_universal_button: /themes/custom/fsa/dist/sprite.svg
universal_button_placement: after
no_3p: false
_core:
  default_config_hash: 8aJF-FDdnrk-N2gLGWFQcLZIpuJZA0BE9NtgXTVJfVk
