default_challenge: recaptcha/reCAPTCHA
description: 'This is to test you are a human in order to prevent automated spam submissions.'
administration_mode: false
allow_on_admin_pages: false
add_captcha_description: true
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: false
_core:
  default_config_hash: pfrv6lPS72f5WG1UB4wHkgQV2invlHwVpaCy_mY-ClQ
