ignored_config_entities:
  0: system.site
  2: config.fsa_ratings
  4: config.fsa_consultations
  6: 'embed.button.document:icon_uuid'
  8: 'embed.button.document:dependencies.content'
  10: 'embed.button.media_entity_embed:icon_uuid'
  12: 'embed.button.media_entity_embed:dependencies.content'
  14: 'embed.button.image:icon_uuid'
  16: 'embed.button.image:dependencies.content'
  18: 'embed.button.node:icon_uuid'
  20: 'embed.button.node:dependencies.content'
  22: key.key
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
