add_page_meta: true
output_terms: true
output_fields: false
group: false
lib_helper: false
entity_meta:
  langcode: langcode
  vid: vid
  uid: uid
  created: created
  status: status
  roles: roles
  name: '0'
enable_ia: false
ia_depth: '3'
ia_category_primary: primaryCategory
ia_category_sub: subCategory
vocabs:
  alerts_allergen: '0'
  audience: '0'
  consultations_type: '0'
  content_type: '0'
  document_category: '0'
  fhrs_businesstype: '0'
  fhrs_region: '0'
  icons: '0'
  nation: '0'
  news_type: '0'
  research_programme: '0'
  research_topic: '0'
  tags: '0'
  topic: '0'
expose_user_details: ''
expose_user_details_roles:
  authenticated: '0'
  author: '0'
  editor: '0'
  fsa_admin: '0'
  administrator: '0'
expose_user_details_fields: false
entity_title: entityTitle
entity_type: entityType
entity_bundle: entityBundle
entity_identifier: entityId
group_key: groupLabel
drupal_language: drupalLanguage
drupal_country: drupalCountry
site_name: siteName
key_replacements: {  }
_core:
  default_config_hash: 5HzMwTFN-AaoQ2r_UmGvyMhvIwmbgyWKsPiB11y-MwU
