site_key: 6LePUUUUAAAAAJKxaqmTOYwN-Z7Rnvnt3FqsupIR
secret_key: 6LePUUUUAAAAAGMjllg5NA5lvhIRo_3HVecq8evn
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
