<?php

/**
 * @file
 * Contains fsa_consultations.module.
 */

/**
 * Implements template_preprocess_node().
 */
function fsa_consultations_preprocess_node(&$variables) {
  $node = $variables['node'];
  if ($node->getType() == 'consultation' && $variables['view_mode'] == 'full') {
    $variables['content']['#prefix'] = '<div class="consultation-standard-text">';
    $variables['content']['#suffix'] = '</div>';

    $tid = $node->field_consultations_type;
    if (isset($tid->target_id) && $tid->target_id == '215') {
      // // Get the consultation standard text and append to the bottom of
      // content if consultation type is "Consultation" (term id 215).
      $config = \Drupal::config('config.fsa_consultations');
      $variables['content']['standard_text'] = [
        '#markup' => check_markup($config->get('consultation_standard_text'), 'full_html'),
        '#weight' => 50,
      ];
    }

    // Remove metadata from rapidly developing policy nodes.
    if (isset($tid->target_id) && $tid->target_id == '217') {
      if (isset($variables['content']['field_status'])) {
        $variables['content']['field_status'] = [];
      }
      if (isset($variables['content']['field_consultation_launch_date'])) {
        $variables['content']['field_consultation_launch_date'] = [];
      }
      if (isset($variables['content']['field_consultation_closing_date'])) {
        $variables['content']['field_consultation_closing_date'] = [];
      }
    }
  }

  // Get consultation dates and concatenate to be used on promo date field.
  // @todo: A twig template if we start getting more of these start/end dates.
  $consultation_dates = '';
  if (isset($node->field_consultation_launch_date[0])) {
    $consultation_dates .= '<span class="start">' . $node->field_consultation_launch_date->view()[0]['#text'] . '</span>';
  }
  if (isset($node->field_consultation_closing_date[0])) {
    if ($consultation_dates != '') {
      $consultation_dates .= ' <span class="divider">' . t('to') . '</span> ';
    }
    $consultation_dates .= '<span class="end">' . $node->field_consultation_closing_date->view()[0]['#text'] . '</span>';
  }
  $variables['consultation_dates'] = ['#markup' => $consultation_dates];
}
