<?php

/**
 * @file
 * Contains fsa_alerts.module.
 */

use Drupal\fsa_alerts\FsaAlertsHelper;

/**
 * Implements template_preprocess_node().
 */
function fsa_alerts_preprocess_block(&$variables) {

  if ($variables['plugin_id'] == 'page_title_block') {
    $node = \Drupal::routeMatch()->getParameter('node');
    // Override a generic title for page title block when alert type.
    if (is_object($node) && $node->getType() == 'alert') {
      if ($variables['elements']['#id'] == 'pagetitle_hero') {
        $variables['content']['#title'] = t('News and alerts');
      }
    }
  }
}

/**
 * Implements template_preprocess_node().
 */
function fsa_alerts_preprocess_node(&$variables) {

  // Set vars for easy access.
  $node = $variables['node'];

  if ($node->getType() == 'alert' && $variables['view_mode'] == 'full' && $node->hasField('field_alert_type')) {

    // Append "about alert/product recall" static copy text to alert nodes.
    switch ($node->get('field_alert_type')->getString()) {
      case 'AA':
        $about_title = t('About allergy alerts');
        $about_copy = t("Sometimes there will be a problem with a food product that means it should not be sold. Then it might be 'withdrawn' (taken off the shelves) or 'recalled' (when customers are asked to return the product). Sometimes foods have to be withdrawn or recalled if there is a risk to consumers because the allergy labelling is missing or incorrect or if there is any other food allergy risk. When there is a food allergy risk, the FSA will issue an Allergy Alert.");
        break;

      case 'PRIN':
      case 'FAFA':
        $about_title = t('About product recalls and withdrawals');
        $about_copy = t("If there is a problem with a food product that means it should not be sold, then it might be 'withdrawn' (taken off the shelves) or 'recalled' (when customers are asked to return the product). The FSA issues Product Withdrawal Information Notices and Product Recall Information Notices to let consumers and local authorities know about problems associated with food. In some cases, a 'Food Alert for Action' is issued. This provides local authorities with details of specific action to be taken on behalf of consumers.");
        break;

      default:
        $about_title = '';
        $about_copy = '';
        break;
    }

    if ($about_title != '' && $about_copy != '') {
      $variables['content']['about_allergy_alerts'] = [
        '#markup' => '<div class="field__about_alert_description"><h3>' . $about_title . '</h3><p>' . $about_copy . '</p></div>',
        '#weight' => 48,
      ];
    }

    // Display alert ref number after the static text(s).
    if ($node->hasField('field_alert_notation')) {
      $field_alert_notation = $node->field_alert_notation->view(['label' => 'inline']);
      $variables['content']['alert_ref'] = [
        '#markup' => '<p class="field__field_alert_notation">' . $field_alert_notation['#title'] . ' ' . $node->field_alert_notation->getString() . '</p>',
        '#weight' => 49,
      ];
    }

    // Add "Subscribe to alerts CTA".
    $variables['content']['subscribe_alerts'] = [
      '#markup' => '<div class="field__subscribe_alerts">' . FsaAlertsHelper::ctaSubscribe()->toString() . '</div>',
      '#weight' => 50,
    ];
  }

}

/**
 * Implements hook_theme().
 */
function fsa_alerts_theme() {
  return [
    'fsa_alerts_subscribe_hero' => [
      'variables' => [
        'attributes' => NULL,
        'title' => NULL,
        'copy' => NULL,
        'cta' => NULL,
      ],
    ],
  ];
}
