# See https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/ for docs.
version: 1.1.0
services:
  - php:
      version: 7.2
variables:
  global:
    ENV: pipelines
events:
  build:
    steps:
      # Deploy the build artifact to a Cloud on-demand environment.
      - deploy:
          script:
            # Being careful, just do a deployment for develop for now...
            - if [[ "$SOURCE_VCS_PATH" =~ ^develop$ ]]; then pipelines-deploy ;fi
