# See https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/ for docs.
version: 1.1.0
services:
  - php:
      version: 7.1
variables:
  global:
    ENV: pipelines
events:
  build:
    steps:
      - build:
          type: script
          script:
            - composer install
  post-deploy:
    steps:
      - build:
          type: script
          script:
            - drush @foodgovuk.prod updb
            - drush @foodgovuk.prod cim -y
            - drush @foodgovuk.prod cr