# See https://docs.acquia.com/acquia-cloud/develop/pipelines/yaml/ for docs.
version: 1.1.0
services:
  - php:
      version: 7.1
variables:
  global:
    ENV: pipelines
events:
  build:
    steps:
      # By default, the pipelines feature prepends scripts with set -e, which causes the script to exit immediately if any command has a non-zero exit code. You can override this behavior by including set +e in your build script. Be aware that if you use set +e, the script does not fail when a command fails, and so it is the responsibility of the script to manage its own exit strategy and exit codes.
      - composer:
          type: script
          script:
            - composer install --no-interaction --optimize-autoloader
      - test-static-analysis:
          type: script
          script:
            - '${SOURCE_DIR}/phpcs.sh "${SOURCE_DIR}" "${SOURCE_DIR}/docroot/modules/custom ${SOURCE_DIR}/docroot/themes/custom/fsa"'