clone:
  depth: full

pipelines:
  branches:
    master:
      - step:
          name: Build Drupal
          image: wodby/drupal-php:7.2-dev
          caches:
            - drush
          script:
            - make pipelines-build-drupal
          artifacts:
            - 'docroot/**'
            - 'vendor/**'
            - 'web'
      - step:
          name: Build Front-End
          image:
            name: node:11
            run-as-user: 1000
          caches:
            - node
          script:
            - make pipelines-build-frontend
          artifacts:
            - 'docroot/themes/custom/fsa/dist/**'
         #   - 'docroot/themes/custom/fsa/node_modules/**'
      - step:
          name: Relay
          image: deeson/deployer
          script:
            - make pipelines-deploy
    develop:
      - step:
          name: Build Drupal
          image: wodby/drupal-php:7.2-dev
          caches:
            - composer
            - drush
          script:
            - make pipelines-build-drupal
          artifacts:
            - 'docroot/**'
            - 'vendor/**'
            - 'web'
      - step:
          name: Build Front-End
          image:
            name: node:11
            run-as-user: 1000
          caches:
            - node
          script:
            - make pipelines-build-frontend
          artifacts:
            - 'docroot/themes/custom/fsa/dist/**'
           # - 'docroot/themes/custom/fsa/node_modules/**'
      - step:
          name: Relay
          image: deeson/deployer
          script:
            - make pipelines-deploy
    UAT:
      - step:
          name: Build Drupal
          image: wodby/drupal-php:7.2-dev
          caches:
            - composer
            - drush
          script:
            - make pipelines-build-drupal
          artifacts:
            - 'docroot/**'
            - 'vendor/**'
            - 'web'
      - step:
          name: Build Front-End
          image:
            name: node:11
            run-as-user: 1000
          caches:
            - node
          script:
            - make pipelines-build-frontend
          artifacts:
            - 'docroot/themes/custom/fsa/dist/**'
            #- 'docroot/themes/custom/fsa/node_modules/**'
      - step:
          name: Relay
          image: deeson/deployer
          script:
            - make pipelines-deploy
    accessibility:
      - step:
          name: Build Drupal
          image: wodby/drupal-php:7.2-dev
          caches:
            - drush
          script:
            - make pipelines-build-drupal
          artifacts:
            - 'docroot/**'
            - 'vendor/**'
            - 'web'
      - step:
          name: Build Front-End
          image:
            name: node:11
            run-as-user: 1000
          caches:
            - node
          script:
            - make pipelines-build-frontend
          artifacts:
            - 'docroot/themes/custom/fsa/dist/**'
            #- 'docroot/themes/custom/fsa/node_modules/**'
      - step:
          name: Relay
          image: deeson/deployer
          script:
            - make pipelines-deploy
    release/*:
      - step:
          name: Build Drupal
          image: wodby/drupal-php:7.2-dev
          caches:
            - drush
          script:
            - make pipelines-build-drupal
          artifacts:
            - 'docroot/**'
            - 'vendor/**'
            - 'web'
      - step:
          name: Build Front-End
          image:
            name: node:11
            run-as-user: 1000
          caches:
            - node
          script:
            - make pipelines-build-frontend
          artifacts:
            - 'docroot/themes/custom/fsa/dist/**'
            #- 'docroot/themes/custom/fsa/node_modules/**'
      - step:
          name: Relay
          image: deeson/deployer
          script:
            - make pipelines-deploy
  tags:
    '*':
      - step:
          name: Build Drupal
          image: wodby/drupal-php:7.2-dev
          caches:
            - composer
            - drush
          script:
            - make pipelines-build-drupal
          artifacts:
            - 'docroot/**'
            - 'vendor/**'
            - 'web'
      - step:
          name: Build Front-End
          image:
            name: node:11
            run-as-user: 1000
          caches:
            - node
          script:
            - make pipelines-build-frontend
          artifacts:
            - 'docroot/themes/custom/fsa/dist/**'
            #- 'docroot/themes/custom/fsa/node_modules/**'
      - step:
          name: Relay
          image: deeson/deployer
          script:
            - make pipelines-deploy

definitions:
  caches:
    drush: ~/.drush/cache
    node: src/frontend/node_modules
