<?php

/**
 * @file
 * Adds custom webform functionality.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\WebformSubmissionInterface;
use Drupal\webform\WebformInterface;

/**
 * Implements hook_form_alter().
 *
 * Adds a copy of "Save" button to webform submission edit form. Also removes
 * Continue and Previous buttons from webform submission edit form where they
 * make little sense.
 *
 * This simplifies the process of saving a webform submission entity without
 * requiring to go through every webform page.
 */
function fsa_webform_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Target specific webforms.
  $webform_ids = [
    'foreign_object',
    'poor_hygiene_practices',
    'food_poisoning',
  ];

  if (isset($form['#webform_id']) && in_array($form['#webform_id'], $webform_ids) && strpos($form_id, 'webform_submission_') === 0) {
    $form_object = $form_state->getFormObject();
    /** @var \Drupal\webform\WebformSubmissionInterface $webform_submission */
    $webform_submission = $form_object->getEntity();

    // Work only in edit context.
    if (!$webform_submission->isNew()) {
      // Only administrative roles are allowed to see the save button.
      if ($update_permission = !empty(array_intersect(['fsa_admin', 'administrator'], \Drupal::currentUser()->getRoles()))) {
        // Copy submit button into a new "save" button.
        $form['actions']['save'] = $form['actions']['submit'];
        $form['actions']['save']['#access'] = $update_permission;
        array_unshift($form['actions']['save']['#submit'], 'fsa_webform_submit');

        // Create message handler instance. It will send out the message.
        /** @var \Drupal\fsa_webform\WebformSubmissionMessageHandler $message_handler */
        $message_handler = \Drupal::service('class_resolver')->getInstanceFromDefinition('\Drupal\fsa_webform\WebformSubmissionMessageHandler');
        // Set message handler ID.
        $message_handler->setMessageHandlerId('copy_to_la');

        // Create "Save and send to local authority" button.
        $form['actions']['save_and_send_to_la'] = [
          '#type' => 'submit',
          '#value' => t('Save and send to local authority'),
          '#access' => $update_permission,
          '#states' => [
            'visible' => [
              ':input[name="manually_sent"]' => ['checked' => TRUE],
            ],
          ],
          '#weight' => 15,
          '#validate' => $form['actions']['submit']['#validate'],
          '#submit' => array_merge($form['actions']['submit']['#submit'], [[$message_handler, 'sendWebformSubmission']]),
        ];

        // Remove preview/wizard prev/next buttons when in edit context.
        foreach (['preview_prev', 'wizard_prev', 'preview_next', 'wizard_next'] as $button_name) {
          if (isset($form['actions'][$button_name])) {
            $form['actions'][$button_name]['#access'] = FALSE;
          }
        }
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Stops webform from saving the IP address of the submitting user.
 */
function fsa_webform_webform_submission_presave(WebformSubmissionInterface $entity) {
  $entity->remote_addr->value = NULL;
}

function fsa_webform_submit(array &$form, FormStateInterface $form_state) {
  $form_state->set('current_page', WebformInterface::PAGE_CONFIRMATION);
}
