<?php

/**
 * @file
 * Custom 40x page functionalities.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;

/**
 * Implements block_access().
 */
function fsa_40x_block_access(Block $block, $operation, AccountInterface $account) {

  // Be sure breadcrumbs and page titles are not shown on error pages.
  if (in_array($block->id(), ['breadcrumbs', 'pagetitle', 'pagetitle_hero'])) {
    $routename = \Drupal::routeMatch()->getRouteName();
    if (substr($routename, 0, 9) == 'system.40') {
      return AccessResult::forbidden()
        ->addCacheableDependency($block);
    }
  }
}

/**
 * Implements hook_theme().
 */
function fsa_40x_theme() {
  return [
    'fsa_40x_response' => [
      'variables' => [
        'status_code' => NULL,
        'error' => NULL,
        'content' => NULL,
      ],
    ],
  ];
}
