<?php

/**
 * @file
 * Formats output of FSA authorites view email overriden exposed filter options.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function fsa_authorities_exp_filter_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'views_exposed_form') {
    if ($form['#id'] == 'views-exposed-form-fsa-authorities-page-1') {
      $form['field_email_overridden_value']['#options'][1] = t('Yes');
      $form['field_email_overridden_value']['#options'][0] = t('No');
      $form['field_contact_directly_value']['#options'][1] = t('Yes');
      $form['field_contact_directly_value']['#options'][0] = t('No');
    }
  }
}
