<?php

/**
 * @file
 * Contains fsa_research.module.
 */

use Drupal\taxonomy\Entity\Term;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess_page_title().
 */
function fsa_research_preprocess_page_title(&$variables) {
  $route = \Drupal::routeMatch();
  $routename = $route->getRouteName();

  // Prepend research programme ID to page title.
  if ($routename == 'entity.taxonomy_term.canonical' && $term = Term::load($route->getRawParameters()->all()['taxonomy_term'])) {
    if ($term->getVocabularyId() == 'research_programme' && $term->field_rp_id->value != '') {
      $variables['title']['#markup'] = $variables['title']['#markup'] . ' ' . $term->field_rp_id->value;
    }
  }
}

/**
 * Implements hook_preprocess_field().
 */
function fsa_research_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_research_programme') {
    // Prepend the project id.
    if (isset($variables['items'][0]['content']['#options']['entity']->field_rp_id->value)) {
      $variables['items'][0]['content']['#title'] .= ' ' . $variables['items'][0]['content']['#options']['entity']->field_rp_id->value;
    }

  }
}

/**
 * Implements hook_views_pre_view().
 */
function fsa_research_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  if ($view->id() == 'taxonomy_term' && $display_id === 'page' && is_numeric($args[0])) {
    $term = Term::load($args[0]);
    if (isset($term) && $term->getVocabularyId() == 'research_programme') {
      // Append title of listing to the views header.
      $options = array(
        'id' => 'area_text_custom',
        'table' => 'views',
        'field' => 'area_text_custom',
        'relationship' => 'none',
        'group_type' => 'none',
        'admin_label' => '',
        'empty' => TRUE,
        'tokenize' => FALSE,
        'content' => '<h3>' . t('Research projects related to the programme') . '</h3>',
        'plugin_id' => 'text_custom',
      );
      $view->setHandler('page', 'header', 'area_text_custom', $options);
    }
  }
}

/**
 * Implements template_preprocess_views_view_field().
 */
function fsa_research_preprocess_views_view_field(&$variables) {
  $route = \Drupal::routeMatch();
  $routename = $route->getRouteName();
  if ($routename == 'entity.taxonomy_term.canonical' && $term = Term::load($route->getRawParameters()->all()['taxonomy_term'])) {
    // Add "Results available" tag for research programme body results if the
    // checkbox is selected on research node.
    if ($term->getVocabularyId() == 'research_programme' &&
          $variables['field']->field == 'body' &&
          $variables['row']->_entity->field_results_available->value) {
      $variables['output'] = ['#markup' => $variables['output'] .= '<div class="results-available">' . $variables['row']->_entity->field_results_available->view()[0]['#markup'] . '</div>'];
    }
  }
}
