<?php

/**
 * @file
 * Contains fsa_research.module.
 */

use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_preprocess_page_title().
 */
function fsa_research_preprocess_page_title(&$variables) {
  $route = \Drupal::routeMatch();
  $routename = $route->getRouteName();

  // Prepend research programme ID to page title.
  if ($routename == 'entity.taxonomy_term.canonical' && $term = Term::load($route->getRawParameters()->all()['taxonomy_term'])) {
    if ($term->getVocabularyId() == 'research_programme' && $term->field_rp_id->value != '') {
      $variables['title']['#markup'] = $variables['title']['#markup'] . ' ' . $term->field_rp_id->value;
    }
  }
}

/**
 * Implements hook_preprocess_field().
 */
function fsa_research_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_research_programme') {
    // Prepend the project id.
    if (isset($variables['items'][0]['content']['#options']['entity']->field_rp_id->value)) {
      $variables['items'][0]['content']['#title'] .= ' ' . $variables['items'][0]['content']['#options']['entity']->field_rp_id->value;
    }

  }
}
