settings:
  default_submit_button_label: Cyflwyno
  default_reset_button_label: Ailosod
  default_wizard_prev_button_label: Previous
  default_wizard_next_button_label: Continue
  default_preview_next_button_label: Rhagolwg
  default_preview_prev_button_label: Previous
  default_preview_label: Rhagolwg
  default_preview_message: 'Here are the details you are about to report.'
  default_confirmation_back_label: 'Yn ôl at y ffurflen'
element:
  empty_message: '{Gwag}'
