---

- hosts: prod-search
  user: root
  roles:
   - { role: base, tags: [ 'base' ] }
   - { role: papertrail, tags: [ 'papertrail' ] }
   - { role: elasticsearch, tags: [ 'elasticsearch' ] }
   - { role: monit, tags: [ 'monit' ] }
   - { role: newrelic-infra, tags: [ 'newrelic-infra' ] }
   - { role: newrelic-sysmon, tags: [ 'newrelic-sysmon' ] }

  tasks:

  vars_files:
  - prod-vars.yml

  vars:
    ## Base ##

    # On default we disable iptables but we want option to keep it on for customer-servers without external firewall
    #disable_iptables: True

    ## Elasticsearch ##
    # See ansible/playbook/roles/elasticsearch/defaults/main.yml for reference
    elasticsearch_heap_size: 2g

    ## Monit ##
    monit_enabled: True
    monit_alert_email_service_name: "{{ project_name }} search {{ ansible_nodename }}"
    monit_alert_email_from: "{{ support_email }}"
    monit_alert_email_to: "{{ support_email }}"
    monit_allow:
      - localhost
      - 127.0.0.1

    monit_check_sshd: True
    monit_check_remote_syslog: True
    monit_check_cron: True

    # Which ever you are using
    monit_check_elasticsearch: True

    ## Papertrail ##
    papertrail_enabled: True
    papertrail_remote_syslog2_version: "0.16"
    papertrail_conf: "/etc/log_files.yml"
    papertrail_logs:
      - /var/log/secure

    # papertrail host and port defined in prod-vars.yml

    ## Newrelic ##
    newrelic_enabled: True
    newrelic_infra_enabled: True
    # newrelic_license_key defined in prod_vars.yml


