views.filter.fsa_guidance_content_type:
  type: views.filter.many_to_one

views.filter.fsa_consultation_responses_published:
  type: views.filter.many_to_one

block.settings.search_keyword:
  type: block_settings
  label: 'Search keyword settings'
  mapping:
    form_element:
      type: mapping
      label: 'Search keyword block form settings'
      mapping:
        title:
          type: label
          label: 'Title'
        placeholder:
          type: label
          label: 'Placeholder'

block.settings.fsa_link_tabs:
  type: block_settings
  label: 'Search link tab settings'
  mapping:
    links:
      type: mapping
      label: 'Tab settings'
      mapping:
        link-0:
          type: mapping
          label: 'Link 0'
          mapping:
            text:
              type: label
              label: 'Text'
        link-1:
          type: mapping
          label: 'Link 1'
          mapping:
            text:
              type: label
              label: 'Text'
        link-2:
          type: mapping
          label: 'Link 2'
          mapping:
            text:
              type: label
              label: 'Text'
        link-3:
          type: mapping
          label: 'Link 3'
          mapping:
            text:
              type: label
              label: 'Text'
        link-4:
          type: mapping
          label: 'Link 4'
          mapping:
            text:
              type: label
              label: 'Text'
