<?php

/**
 * @file
 * Contains fsa_contactus.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\fsa_custom\FsaCustomHelper;
use Drupal\block\Entity\Block;

/**
 * Implements hook_webform_element_alter().
 */
function fsa_contactus_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  // Add custom data attributes to all elements.
  $extra_classes = [];
  if (isset($element['#type'])) {
    $extra_classes[] = $element['#type'];
    if (isset($element['#format'])) {
      $extra_classes[] = $element['#format'];
    }
    $extra_classes[] = $element['#webform_key'];
    foreach ($extra_classes as $c) {
      $element['#attributes']['class'][] = $c;
    }
  }

  // Mark optional elements as suggested by GDS, do not apply on fieldsets,
  // pages etc.
  $ignored_elements = ['fieldset', 'webform_wizard_page'];
  if ((!isset($element['#required']) && isset($element['#title'])) && !isset($element['#states']['required']) && !in_array($element['#type'], $ignored_elements)) {
    $element['#title'] = $element['#title'] . ' <span class="optional">(' . t('optional') . ')</span>';
  }

  // Rewrite rafp privacy notice field to the required link.
  if ($element['#webform_key'] == 'fsa_privacy_link_rafp') {
    $element['#markup'] = FsaCustomHelper::privacyNoticeLink('rafp');
  }

  // Rewrite ncfu privacy notice field to the required link.
  if ($element['#webform_key'] == 'fsa_privacy_link_nfcu') {
    $element['#markup'] = FsaCustomHelper::privacyNoticeLink('nfcu');
  }

}

/**
 * Implements template_preprocess_webform_progress().
 */
function fsa_contactus_preprocess_webform_progress(array &$variables) {

  if (isset($variables['summary'])) {
    // Change webform default "Page ..." to "Step ...".
    $variables['summary'] = t('Step @start of @end', $variables['summary']->getArguments());
  }
}

/**
 * Implements template_preprocess_webform_container_base_html().
 *
 * @param array $variables
 *   Fieldset element.
 */
function fsa_contactus_preprocess_webform_container_base_html(array &$variables) {

  if (isset($variables['webform_submission']) && isset($variables['value']['#id'])) {
    if ($audience = $variables['webform_submission']->getElementData('audience')) {

      // Get fieldset identifier.
      $id = $variables['value']['#id'];

      // Conditionally remove fieldset. Business fields should be hidden from
      // the consumer, and visa versa.
      $con_bus = $audience == 'consumer' && $id == 'food_fraud_crime--business';
      $bus_con = $audience == 'business' && $id == 'food_fraud_crime--consumer';
      if ($con_bus || $bus_con) {
        $variables = [];
      }
    }
  }

}

/**
 * Implements template_preprocess_webform().
 */
function fsa_contactus_preprocess_webform(array &$variables) {

  // Webforms id's to attach the user satisfaction form to.
  $webform_ids = [
    'foreign_object',
    'poor_hygiene_practices',
    'food_poisoning',
    'food_fraud_crime',
  ];
  if (isset($variables['element']['#webform_id']) && in_array($variables['element']['#webform_id'], $webform_ids)) {
    $form_page = \Drupal::request()->query->get('page');
    if ($form_page == 'webform_confirmation') {
      if (is_object($block = Block::load('user_satisfaction_form'))) {

        // Add js to accordion the feedback form.
        $variables['#attached']['library'][] = 'fsa_contactus/user_satisfaction';

        $block = \Drupal::entityTypeManager()->getViewBuilder('block')->view($block);
        $variables['satisfaction_form'] = render($block);
      }
    }
  }
}
