<?php

/**
 * @file
 * Contains fsa_contactus.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_element_alter().
 */
function fsa_contactus_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  // Add custom data attributes to all elements.
  $extra_classes = [];
  if (isset($element['#type'])) {
    $extra_classes[] = $element['#type'];
    if (isset($element['#format'])) {
      $extra_classes[] = $element['#format'];
    }
    $extra_classes[] = $element['#webform_key'];
    foreach ($extra_classes as $c) {
      $element['#attributes']['class'][] = $c;
    }
  }
}

/**
 * Implements template_preprocess_webform_progress().
 */
function fsa_contactus_preprocess_webform_progress(array &$variables) {

  if (isset($variables['summary'])) {
    // Change webform default "Page ..." to "Step ...".
    $variables['summary'] = t('Step @start of @end', $variables['summary']->getArguments());
  }
}
