<?php

/**
 * @file
 * Contains fsa_ratings.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function fsa_ratings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fsa_ratings module.
    case 'help.page.fsa_ratings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('FSA Ratings module creates entities to store data from UK Food Hygiene Rating Scheme (FHRS) API V2') . '</p>';
      $output .= '<ul>';
      $output .= '<li>' . t('<strong>FSA Authorities</strong> for storing FHRS authorities as returned from <code><a href="http://api.ratings.food.gov.uk/Help/Api/GET-Authorities">GET Authorities</a></code>') . '</li>';
      $output .= '<li>' . t('<strong>FSA Establishments</strong> for storing FHRS establishments as returned from <code><a href="http://api.ratings.food.gov.uk/Help/Api/GET-Establishments-id">GET Establishments</a></code>') . '</li>';
      $output .= '</ul>';
      $output .= '<p>' . t('FSA Food Hygiene Rating Scheme API module creates entities to store data from FHRS API') . '</p>';
      $output .= '<p>' . t('<a href="http://api.ratings.food.gov.uk">Read more about FHRS API</a>') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_preprocess_field().
 */
function fsa_ratings_preprocess_field(&$variables, $hook) {
  if ($variables['element']['#field_name'] == 'field_righttoreply') {
    // Remove line-breaks, empty paragrahps and HtmlDecode the field content.
    $righttoreply = preg_replace(["/\r|\n/", "/<p[^>]*>[\s|&nbsp;]*<\/p>/"], '', Html::decodeEntities($variables['items'][0]['content']['#context']['value']));
    $variables['items'][0]['content']['#context']['value'] = ['#markup' => $righttoreply];
  }

  if ($variables['element']['#field_name'] == 'field_newratingpending') {
    if ($variables['items'][0]['content']['#markup'] === 'true') {
      $variables['items'][0]['content']['#markup'] = t('Recently inspected. New rating to be published soon.');
    }
    else {
      unset($variables['items'][0]['content']);
    }
  }

  // Process address field contents.
  if ($variables['element']['#field_name'] == 'field_address') {
    $address_value = $variables['items'][0]['content']['#context']['value'];

    // Remove blank lines produced by API content.
    $address_display = preg_replace("/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/", "\n", $address_value);

    // If API does not provide address we can assume it is a private property.
    if (trim($address_value) == '') {

      // Get the authority name to be displayed with "Private address" text.
      $la_id = $variables['element']['#object']->get('field_localauthoritycode')->getValue()[0]['target_id'];
      $la = Drupal::entityTypeManager()->getStorage('fsa_authority')->load($la_id);

      $address_display = t('Private address: registered with @la', ['@la' => $la->getName()]);
    }

    $variables['items'][0]['content']['#context']['value'] = ['#markup' => $address_display];
  }
}

/**
 * Implements template_preprocess_pager().
 */
function fsa_lander_preprocess_pager(&$variables) {
  $route = \Drupal::routeMatch();
  // Prepend "#results" anchor to pager links on ratings search page.
  if ($route->getParentRouteMatch()->getRouteName() == 'fsa_ratings.ratings_search') {

    // Modify first/prev/next/last links.
    $first_prev = ['first', 'prev', 'next', 'last'];
    foreach ($first_prev as $item) {
      if (isset($variables['items'][$item])) {
        $variables['items'][$item]['href'] = $variables['items'][$item]['href'] . '#results';
      }
    }

    // Modify pager links.
    if (isset($variables['items']['pages'])) {
      $page = 1;
      foreach ($variables['items']['pages'] as $key => $value) {
        $variables['items']['pages'][$page]['href'] = $value['href'] . '#results';
        $page++;
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function fsa_ratings_theme() {

  return [
    'fsa_establishment' => [
      'render element' => 'children',
      'variables' => [
        'search_form' => NULL,
        'content' => NULL,
        'rating_value' => NULL,
        'rating_badge' => NULL,
        'backlink' => NULL,
        'find_more_title' => t('Find out more about food hygiene ratings'),
        'find_more_link_ratings' => NULL,
        'find_more_link_fhrs' => NULL,
        'righttoreply_title' => t('About comments made by the business'),
        'righttoreply_copy' => t('A business has the right to reply to its local authority about the food hygiene rating given. This means a business may draw attention to improvements made since the inspection and/or explain particular circumstances at the time of inspection that might have affected the rating the business was given. The comments made by the business have been reviewed and may have been edited by a local authority food safety officer so they fit the terms and conditions of this website but the accuracy of any statements made has not been verified.'),
        'business_owner_title' => t('Are you the business owner or manager?'),
        'business_owner_copy1' => t('If any information on this page is incorrect you can email the correct information to your local authority by using the email address below.'),
        'business_owner_copy2' => t('You can find out how to appeal against the rating given and find out about your right to reply. You can also ask for a re-inspection.'),
        'rating_badge_title' => t('Display this rating on your website'),
        'rating_badge_copy' => t('You can display this rating on your website.'),
        'rating_badge_cta' => NULL,
        'copy_of_report_title' => t('Do you want to get a copy of the report?'),
        'copy_of_report_copy' => t('If you wish to see the food safety officer’s report on which this rating is based, you can request this from the local authority that carried out the inspection. You can do this by sending an email to the address below. The local authority will consider your request and will usually send you a copy of the report. In some cases, the local authority may decide that they cannot do so but will let you know this and explain why.'),
      ],
    ],

    // Ratings meaning page. Created by fsa_ratings.ratings_meanings route.
    'fsa_ratings_meanings' => [
      'render element' => 'custom_element',
      'variables' => [
        'search_form' => NULL,
        'ratings' => [],
        'backlink' => NULL,
        'paragraph_1' => NULL,
        'paragraph_2' => NULL,
      ],
    ],

    // Ratings meaning item theme, passed for fsa_ratings_meanings template.
    'fsa_ratings_meanings_item' => [
      'render element' => 'custom_element',
      'variables' => [
        'rating_score' => NULL,
        'rating_badge' => NULL,
        'rating_description' => NULL,
      ],
    ],

    // Textual representations for field_score_* values.
    'fsa_ratings_field_score_display' => [
      'render element' => 'children',
      'variables' => [
        'title' => NULL,
        'description' => NULL,
        'score' => NULL,
      ],
    ],
    'fsa_ratings_search_form' => [
      'render element' => 'form',
    ],
    'fsa_ratings_search_page' => [
      'render element' => 'custom_element',
      'variables' => [
        'items' => [],
        'categories' => [],
        'keywords' => '',
        'available_filters' => [],
        'applied_filters' => [],
        'hits_total' => 0,
        'hits_shown' => 0,
        'form' => NULL,
        'sort_form' => NULL,
        'ratings_info_content' => NULL,
        'load_more' => NULL,
      ],
    ],
    'fsa_ratings_search_result_item' => [
      'render element' => 'custom_element',
      'variables' => [
        'item' => NULL,
      ],
    ],
  ];
}
