<?php

/**
 * @file
 * Contains fsa_custom.module.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Session\AccountInterface;
use Drupal\block\Entity\Block;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Link;
use Drupal\Component\Utility\Html;

/**
 * Implements of template_preprocess_html().
 */
function fsa_custom_preprocess_page(&$variables) {

  // Hardcoded links for "utility menu". @todo: make dynamic/editable via CMS.
  $items = [[
    '#markup' => Link::createFromRoute(
      t('Contact'),
      'entity.node.canonical',
      ['node' => '58'],
      [])->toString(),
    '#wrapper_attributes' => [
      'class' => [
        'item',
        'contact',
      ],
    ],
  ],
    [
      '#markup' => Link::createFromRoute(
        t('Food hygiene ratings'),
        'fsa_ratings.ratings_search',
        [],
        [])->toString(),
      '#wrapper_attributes' => [
        'class' => [
          'item',
          'rating',
        ],
      ],
    ],
  ];

  // Build the utility menu.
  $variables['utility_menu'] = [
    '#theme' => 'item_list',
    '#list_type' => 'ul',
    '#wrapper_attributes' => [
      'class' => [
        'wrapper',
      ],
    ],
    '#attributes' => [
      'class' => [
        'menu-utility',
      ],
    ],
    '#items' => $items,
  ];

}

/**
 * Implements hook_preprocess_page_title().
 */
function fsa_custom_preprocess_page_title(&$variables) {

  $route = \Drupal::routeMatch();
  $node = $route->getParameter('node');
  if (is_object($node) && $node->hasField('field_nation')) {
    $nations = $node->get('field_nation');
    // Display nation as title prefix only if just one nation is selected.
    if (isset($nations[0]) && !isset($nations[1])) {
      $nation = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($nations[0]->getValue()['target_id'])->getName();

      // Use same classes as via WYSIWYG for regional variations.
      $class = 'regional-variation regional-variation--' . strtolower(Html::cleanCssIdentifier($nation));
      $variables['title_prefix'] = ['#markup' => '<div class="' . $class . '">' . t('@nation specific', ['@nation' => $nation]) . '</div>'];
    }
  }

}

/**
 * Implements template_preprocess_breadcrumb().
 */
function fsa_custom_preprocess_breadcrumb(&$variables) {

  $node = \Drupal::routeMatch()->getParameter('node');
  if (isset($node)) {

    // Node titles can be horribly long, if that's the case truncate with
    // sensible amount of characters, word-safe.
    $max_length = 90;
    foreach ($variables['breadcrumb'] as $key => $value) {
      if (is_string($variables['breadcrumb'][$key]['text']) && strlen($variables['breadcrumb'][$key]['text']) >= $max_length) {
        $variables['breadcrumb'][$key]['text'] = Unicode::truncate($variables['breadcrumb'][$key]['text'], $max_length, TRUE, TRUE);
      }
    }
  }
}

/**
 * Implements block_access().
 */
function fsa_custom_block_access(Block $block, $operation, AccountInterface $account) {

  if ($operation == 'update' && \Drupal::routeMatch()->getRouteName() == 'entity.block.edit_form') {
    // Let admins know these blocks configuration visibility is controlled in
    // this custom module.
    $controlled_block_ids = [
      'menu_help_secondary',
      'pagetitle',
      'pagetitle_hero',
    ];

    if (in_array($block->id(), $controlled_block_ids)) {
      drupal_set_message(t('<b>NB!</b> this block visibility is controlled in <code>@function</code>', ['@function' => __FUNCTION__ . '()']), 'warning');
    }
  }

  if ($operation == 'view') {
    // Control certain block visibilities based on node type, term etc.
    $node = \Drupal::routeMatch()->getParameter('node');
    if (is_object($node)) {

      $term_id = FALSE;
      if ($node->hasField('field_content_type')) {
        // Get content_type taxonomy term id.
        $tid = $node->get('field_content_type')->target_id;
        if (is_numeric($tid)) {
          $term = Term::load($tid);
          $term_id = $term->id();
        }
      }

      // Control the region for page title block.
      if ($block->getPluginId() == 'page_title_block') {
        // Use content_type taxonomy to define in which region the pagetitle
        // should be displayed.
        switch ($term_id) {
          // News/Alerts.
          case 29:
            if ($block->id() == 'pagetitle') {
              return AccessResult::forbidden()
                ->addCacheableDependency($block);
            }
            break;

          default:
            if ($block->id() == 'pagetitle_hero') {
              // By default completely remove page title from hero region.
              return AccessResult::forbidden()
                ->addCacheableDependency($block);
            }
            break;
        }
      }

      if ($block->id() == 'menu_help_secondary') {
        // Help nodes and nodes with "Content type" term should always show the
        // left hand menu.
        if ($term_id == 27 || $node->getType() == 'help') {
          return AccessResult::allowed()
            ->addCacheableDependency($block);
        }
        else {
          return AccessResult::forbidden()
            ->addCacheableDependency($block);
        }
      }

    }
    else {
      $route = \Drupal::routeMatch();
      // Have few rules for non-nodes to hide the title from hero.
      if ($block->id() == 'pagetitle_hero') {
        if ($route->getParameter('fsa_establishment')) {
          return AccessResult::forbidden()
            ->addCacheableDependency($block);
        }
      }

      // Additional access/visibility rules for non-node pages.
      if ($block->id() == 'menu_help_secondary') {
        return AccessResult::forbidden()
          ->addCacheableDependency($block);
      }
    }
  }
}

/**
 * Implements template_preprocess_block().
 */
function fsa_custom_preprocess_block(&$variables) {

  if ($variables['plugin_id'] == 'page_title_block') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if (is_object($node)) {
      if ($variables['elements']['#id'] == 'pagetitle_hero' && $node->getType() == 'lander') {
        // Visually hide hero region page title for lander CT.
        // We want this h1 in dom for accessibility/SEO.
        $variables['attributes']['class'][] = 'visually-hidden';
      }
    }
  }
}


/**
 * Implements hook_editor_js_settings_alter().
 */
function fsa_custom_editor_js_settings_alter(array &$settings) {

  $formats = [
    'full_html',
    'basic_html',
  ];
  foreach ($formats as $format) {
    // Limit headings/tags of "Format" dropdown.
    $settings['editor']['formats'][$format]['editorSettings']['format_tags'] = "p;h2;h3;h4;h5";
  }
}

/**
 * Implements hook_theme().
 */
function fsa_custom_theme() {
  return [
    'fsa_hero' => [
      'variables' => [
        'attributes' => NULL,
        'title' => NULL,
        'copy' => NULL,
      ],
    ],
  ];
}
