<?php

/**
 * @file
 * Contains fsa_custom.module.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\Core\Session\AccountInterface;
use Drupal\block\Entity\Block;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Link;
use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements of template_preprocess_page().
 */
function fsa_custom_preprocess_page(&$variables) {

  // Attach history back js (allows creating dummy clientside backlinks with
  // ("a.history-back" html class).
  $variables['#attached']['library'][] = 'fsa_custom/history_back';

  // Hardcoded "utility menu" links.
  // Get the contact link from settings. Default to 58 which happened to be the
  // first version contact lander.
  $contact_link = \Drupal::state()->get('fsa_custom.contact_link_nid');
  $contact_nid = (isset($contact_link) && is_numeric($contact_link)) ? $contact_link : 58;
  $items = [[
    '#markup' => Link::createFromRoute(
      t('Contact'),
      'entity.node.canonical',
      ['node' => $contact_nid],
      [])->toString(),
    '#wrapper_attributes' => [
      'class' => [
        'item',
        'contact',
      ],
    ],
  ],
    [
      '#markup' => Link::createFromRoute(
        t('Food hygiene ratings'),
        'fsa_ratings.ratings_search',
        [],
        [])->toString(),
      '#wrapper_attributes' => [
        'class' => [
          'item',
          'rating',
        ],
      ],
    ],
  ];

  // Build the utility menu.
  $variables['utility_menu'] = [
    '#theme' => 'item_list',
    '#list_type' => 'ul',
    '#wrapper_attributes' => [
      'class' => [
        'wrapper',
      ],
    ],
    '#attributes' => [
      'class' => [
        'menu-utility',
      ],
    ],
    '#items' => $items,
  ];

}

/**
 * Implements hook_preprocess_page_title().
 */
function fsa_custom_preprocess_page_title(&$variables) {

  $route = \Drupal::routeMatch();
  $node = $route->getParameter('node');
  if (is_object($node)) {
    $nodetype = $node->getType();
    $typemanager = \Drupal::entityTypeManager();

    // Init the custom title prefix.
    $title_prefix = [];

    if ($node->hasField('field_nation')) {
      $nations = $node->get('field_nation');
      if (isset($nations[0])) {
        // Add regional variations label with same classes as would be added via
        // WYSIWYG editor.
        $class = 'regional-variation';
        $nation_label = '';
        if (!isset($nations[1])) {
          // If only one nation selected.
          $nation = $typemanager->getStorage('taxonomy_term')->load($nations[0]->getValue()['target_id'])->getName();
          $class .= ' regional-variation--' . strtolower(Html::cleanCssIdentifier($nation));
          $nation_label = t('@nation specific', ['@nation' => $nation]);
        }
        elseif (isset($nations[1]) && !isset($nations[2])) {
          // If two nations selected.
          $class .= ' regional-variation--multi-regional';
          $nation_label = t(
            '@nation_1 and @nation_2 specific',
            [
              '@nation_1' => $typemanager->getStorage('taxonomy_term')->load($nations[0]->getValue()['target_id'])->getName(),
              '@nation_2' => $typemanager->getStorage('taxonomy_term')->load($nations[1]->getValue()['target_id'])->getName(),
            ]
          );
        }

        if ($nation_label != '') {
          $title_prefix[] = [
            '#theme' => 'fsa_label',
            '#attributes' => [
              'class' => $class,
            ],
            '#label' => $nation_label,
          ];
        }

      }
    }

    if ($node->hasField('field_consultations_type')) {
      // Add consultation type to title prefix.
      $types = $node->get('field_consultations_type');
      if (isset($types[0])) {
        $consultation_type = $typemanager->getStorage('taxonomy_term')->load($types[0]->getValue()['target_id'])->getName();
        $title_prefix[] = [
          '#theme' => 'fsa_label',
          '#attributes' => [
            'class' => 'consultation-type consultation-type--' . strtolower(Html::cleanCssIdentifier($consultation_type)),
          ],
          '#label' => $consultation_type,
        ];
      }
    }

    if ($nodetype == 'research_project') {
      $title_prefix[] = [
        '#theme' => 'fsa_label',
        '#attributes' => [
          'class' => 'content-type content-type--research',
        ],
        '#label' => t('Research project'),
      ];
    }

    // Inject additional title prefix(es) if there was anything to add.
    if (!empty($title_prefix)) {
      $variables['title_prefix'] = $title_prefix;
    }


  }
  else {
    $route = \Drupal::routeMatch();
    $routename = $route->getParentRouteMatch()->getRouteName();

    // Add a title suffix on signup pages.
    if (substr($routename, 0, 10) == 'fsa_signin') {
      $variables['title_suffix'] = ['#markup' => '<p>' . t('Stay up to date with food and allergy alerts, FSA news and consultations.') . '</p>'];
    }

  }

}

/**
 * Implements template_preprocess_breadcrumb().
 */
function fsa_custom_preprocess_breadcrumb(&$variables) {
  $routematch = \Drupal::routeMatch();

  $node = $routematch->getParameter('node');
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    // We don't need breadcrumbs on homepage.
    unset($variables['breadcrumb']);
  }
  elseif (isset($node)) {
    // Node titles can be horribly long, if that's the case truncate with
    // sensible amount of characters, word-safe.
    $max_length = 90;
    foreach ($variables['breadcrumb'] as $key => $value) {
      if (is_string($variables['breadcrumb'][$key]['text']) && strlen($variables['breadcrumb'][$key]['text']) >= $max_length) {
        $variables['breadcrumb'][$key]['text'] = Unicode::truncate($variables['breadcrumb'][$key]['text'], $max_length, TRUE, TRUE);
      }
    }
  }

  // Alter breadcumbs for term pages.
  $term = $routematch->getParameter('taxonomy_term');
  if (isset($term)) {

    // Topic terms listing pages.
    if ($term->getVocabularyId() == 'topic') {
      // Inject "Topics" as the second item.
      array_splice($variables['breadcrumb'], 1, 0, [['text' => t('Topics'), 'url' => Url::fromRoute('view.a_to_z.page_1')]]);

      // Add name of the term.
      $variables['breadcrumb'][] = [
        'text' => $term->getName(),
        'url' => FALSE,
      ];
    }
  }

}

/**
 * Implements block_access().
 */
function fsa_custom_block_access(Block $block, $operation, AccountInterface $account) {

  if ($operation == 'update' && \Drupal::routeMatch()->getRouteName() == 'entity.block.edit_form') {
    // Let admins know these blocks configuration visibility is controlled in
    // this custom module.
    $controlled_block_ids = [
      'menu_help_secondary',
      'pagetitle',
      'pagetitle_hero',
    ];

    if (in_array($block->id(), $controlled_block_ids)) {
      drupal_set_message(t('<b>NB!</b> this block visibility is controlled in <code>@function</code>', ['@function' => __FUNCTION__ . '()']), 'warning');
    }
  }

  if ($operation == 'view') {
    // Control certain block visibilities based on node type, term etc.
    $node = \Drupal::routeMatch()->getParameter('node');
    if (is_object($node)) {

      $term_id = FALSE;
      if ($node->hasField('field_content_type')) {
        // Get content_type taxonomy term id.
        $tid = $node->get('field_content_type')->target_id;
        if (is_numeric($tid) && $term = Term::load($tid)) {
          $term_id = $term->id();
        }
      }

      // Control the region for page title block.
      if ($block->getPluginId() == 'page_title_block') {

        // Page title above content visibility.
        if ($block->id() == 'pagetitle') {
          // Hide page title on lander nodes.
          if ($node->getType() == 'lander') {
            return AccessResult::forbidden()
              ->addCacheableDependency($block);
          }
        }

        // Use content_type taxonomy to define in which region the pagetitle
        // should be displayed.
        switch ($term_id) {
          // News/Alerts.
          case 29:
            if ($block->id() == 'pagetitle') {
              return AccessResult::forbidden()
                ->addCacheableDependency($block);
            }
            break;

          default:
            if ($block->id() == 'pagetitle_hero') {
              // By default completely remove page title from hero region.
              return AccessResult::forbidden()
                ->addCacheableDependency($block);
            }
            break;
        }
      }

      if ($block->id() == 'menu_help_secondary') {
        // Help nodes and nodes with "Content type" term should always show the
        // left hand menu.
        if ($term_id == 27 || $node->getType() == 'help') {
          return AccessResult::allowed()
            ->addCacheableDependency($block);
        }
        else {
          return AccessResult::forbidden()
            ->addCacheableDependency($block);
        }
      }

    }
    else {
      $route = \Drupal::routeMatch();
      $routename = $route->getParentRouteMatch()->getRouteName();

      // Page title in content area.
      if ($block->id() == 'pagetitle') {

        // Term listing pages.
        if ($routename == 'entity.taxonomy_term.canonical' && $term = Term::load($route->getRawParameters()->all()['taxonomy_term'])) {

          switch ($term->getVocabularyId()) {
            case 'research_programme':
              // Hide hero on research programme pages.
              return AccessResult::allowed()
                ->addCacheableDependency($block);
          }
        }


        // Default to not showing title in content area.
        return AccessResult::forbidden()
          ->addCacheableDependency($block);
      }

      // Page title in hero area.
      if ($block->id() == 'pagetitle_hero') {

        // Enter all speficic routes to remove the page title in hero area.
        $routes = [
          'fsa_signin.user_registration_thank_you',
        ];

        if (in_array($routename, $routes) || $route->getParameter('fsa_establishment')) {
          return AccessResult::forbidden()
            ->addCacheableDependency($block);
        }

        // Term listing pages.
        if ($routename == 'entity.taxonomy_term.canonical' && $term = Term::load($route->getRawParameters()->all()['taxonomy_term'])) {

          switch ($term->getVocabularyId()) {
            case 'research_programme':
              // Hide hero on research programme pages.
              return AccessResult::forbidden()
                ->addCacheableDependency($block);
          }
        }
      }

      // Additional access/visibility rules for non-node pages.
      if ($block->id() == 'menu_help_secondary') {
        return AccessResult::forbidden()
          ->addCacheableDependency($block);
      }
    }
  }
}

/**
 * Implements template_preprocess_block().
 */
function fsa_custom_preprocess_block(&$variables) {

  if ($variables['plugin_id'] == 'page_title_block') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if (is_object($node)) {
      if ($variables['elements']['#id'] == 'pagetitle_hero' && $node->getType() == 'lander') {
        // Visually hide hero region page title for lander CT.
        // We want this h1 in dom for accessibility/SEO.
        $variables['attributes']['class'][] = 'visually-hidden';
      }
    }
    else {
      $route = \Drupal::routeMatch();
      $routename = $route->getParentRouteMatch()->getRouteName();

      // Modify page title in hero area.
      if ($variables['elements']['#id'] == 'pagetitle_hero') {

        // Signin pages.
        if (substr($routename, 0, 10) == 'fsa_signin') {
          $variables['content']['#title'] = t('Subscribe to news and alerts');
        }

      }
    }
  }
}


/**
 * Implements hook_editor_js_settings_alter().
 */
function fsa_custom_editor_js_settings_alter(array &$settings) {

  foreach ($settings['editor']['formats'] as $key => $value) {
    // Limit headings/tags of "Format" dropdown.
    $settings['editor']['formats'][$key]['editorSettings']['format_tags'] = "p;h2;h3";
  }
}

/**
 * Implements hook_theme().
 */
function fsa_custom_theme() {
  return [
    'fsa_hero' => [
      'variables' => [
        'attributes' => NULL,
        'title' => NULL,
        'copy' => NULL,
      ],
    ],
    'image_as_background' => [
      'variables' => [
        'attributes' => NULL,
        'path' => NULL,
      ],
    ],
    'fsa_label' => [
      'variables' => [
        'attributes' => [],
        'label' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_field_widget_form_alter().
 */
function fsa_custom_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {

  // Media provider classes.
  $classes = [
    'media-document-form',
    'media-document-edit-form',
    'media-image-form',
    'media-image-edit-form',
  ];

  // Reset media name field maximum length to 128 characters.
  if (isset($context['form']['#attributes']['class'])) {
    $media_form = array_intersect($classes, $context['form']['#attributes']['class']);
    if ($media_form) {
      $field_definition = $context['items']->getFieldDefinition();
      $name = $field_definition->getName();
      if ($name == 'name') {
        $element['value']['#maxlength'] = 128;
      }
    }
  }
}
