---
# Example site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  aliases: local

  drupal_version: d8

  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - files: web/sites/default/files
    - conf/settings.development.php: web/sites/default/settings.local.php
    - conf/settings.global.php: web/sites/default/settings.global.php

  local_commands:
    new:
      - shell: echo "Use the 'create' command to create a new project and the 'reset' command to join an existing one."

    create:
      - verify: "Type yes to verify you want to create a new installation: "
      - make
      - drush: site-install standard
      - drush: cex -y
      - shell: echo "New installation is complete and configuration has been exported. Please commit it."
      - cleanup

    reset:
      - verify: "Type yes to verify you want to reset your local environment: "
      - make
      - drush: site-install config_installer
      - cleanup

    # Basic site update functionality
    update:
      - backup:
         ignore:
          - builds
      - make
      - drush: updb -y
      - drush: cim -y
      - drush: entity-updates -y
      - cleanup
#      - shell:
#        - vendor/bin/codecept clean -c web/codeception.yml
#        - vendor/bin/codecept run -c web/codeception.yml

    test:
      - shell:
        - vendor/bin/codecept clean -c web/codeception.yml
        - vendor/bin/codecept run -c web/codeception.yml

# Minimal build for Travis CI
ci:
  local_commands:
    build:
      - make
      - shell: chmod -R a+w web

# Test environment:
stage:

  aliases: test

  # Test environment only symlinks files
  link:
    - conf/settings.stage.php: web/sites/default/settings.local.php
    - conf/settings.global.php: web/sites/default/settings.global.php
    - /var/www/fsa/files: web/sites/default/files


  # You can use copy to put some custom files in place if needed
  #copy:
    #- conf/_ping.php: web/_ping.php

  # We can provide local commands or override global ones.
  local_commands:
    create:
      - shell: echo "Creating a new installation should only be done in local environments."

    reset:
      - verify: "Type yes to verify you want to reset your local environment: "
      - backup:
         ignore:
          - builds
      - make
      - drush: site-install config_installer
      - cleanup

    # Basic site update functionality
    build:
      - make

    update:
      - shell: 
        - rm web/sites/default/files
        - ln -s /var/www/fsa/files web/sites/default/files
      - drush: updb -y
      - drush: cim -y
      - drush: entity-updates -y
      - cleanup
      - shell: chmod -R a-w web
      - shell: sudo systemctl restart nginx php-fpm varnish
      #- shell:
      #  - vendor/bin/codecept clean -c web/codeception.yml
      #  - vendor/bin/codecept run -c web/codeception.yml --env test


# Production environment:
production:

  aliases: prod

  # Prod environment only symlinks files
  link:
    - /var/www/fsa.prod.wunder.io/files: web/sites/default/files


  local_commands:
    # Basic site update functionality
    build:
      - backup:
         ignore:
          - builds
          - files
      - shell: chmod -R a+w web
      - make
      - shell: chmod -R a-w web
      - shell: rsync -az . 10.2.3.18:/var/www/fsa.prod.wunder.io/current

    update:
      - drush: updb -y
      - drush: cim -y
      - drush: entity-updates -y
      - drush: cr -y
      - cleanup
      - shell: sudo systemctl restart nginx php-fpm memcached
      - shell: sudo systemctl -H 10.2.3.18 restart nginx php-fpm memcached
      - shell: sudo systemctl -H 10.2.5.150 restart varnish

