<?php

/**
 * @file
 * Enables links to be referenced from a single managed source.
 */

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_token_info().
 */
function fsa_managed_links_token_info() {

  // Load all managed links.
  $data = [
    'managed_links' => [
      'example_company' => [
        'text' => 'example company',
        'url' => 'http://example.com/',
      ],
      'example_organisation' => [
        'text' => 'example organisation',
        'url' => 'http://example.org/',
      ],
    ],
  ];

  // Generate tokens array.
  $tokens = [];
  foreach ($data['managed_links'] as $key => $link) {
    $tokens['managed_link'][$key] = [
      'name' => $link['text'],
      'description' => $link['url'],
      'needs-data' => 'managed_links',
    ];
  }

  // Provide token information.
  return [
    'types' => [
      'managed_link' => [
        'name' => t('Managed links'),
        'description' => t('Managed link tokens.'),
      ],
    ],
    'tokens' => $tokens,
  ];
}

/**
 * Implements hook_tokens().
 */
function fsa_managed_links_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {

  // Provide replacement values for tokens.
  $replacements = [];
  if ($type == 'managed_link') {
    foreach ($tokens as $key => $token) {
      $text = $data['managed_links'][$key]['text'];
      $url = $data['managed_links'][$key]['url'];
      $replacements[$token] = Link::fromTextAndUrl($text, Url::fromUri($url, []))->toString();
    }
  }
  return $replacements;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function fsa_managed_links_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  // Load all managed links.
  $data = [
    'managed_links' => [
      'example_company' => [
        'text' => 'example company',
        'url' => 'http://example.com/',
      ],
      'example_organisation' => [
        'text' => 'example organisation',
        'url' => 'http://example.org/',
      ],
    ],
  ];

  // Replace tokens with their replacement values.
  if ($build['#node']->hasField('body')) {
    $body = $build['#node']->get('body')->getValue();
    $text = $body[0]['value'];
    $build['body'][0]['#text'] = \Drupal::token()->replace($text, $data);
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function fsa_managed_links_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Add token tree links under body widget.
  $form['body']['managed_links'] = array(
    '#theme' => 'token_tree_link',
    '#token_types' => ['managed_link'],
    '#global_types' => FALSE,
    '#text' => t('Insert managed link'),
  );
}
