<?php

/**
 * @file
 * Contains fsa_establishment_lookup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fsa_establishment_lookup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fsa_establishment_lookup module.
    case 'help.page.fsa_establishment_lookup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('fsa_establishment_lookup adds Google Places search to look for businesses.') . '</p>';

      return $output;

    default:
  }

  return FALSE;
}
