<?php

/**
 * @file
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fsa_ratings_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fsa_ratings_import module.
    case 'help.page.fsa_ratings_import':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('FSA Ratings Import module migrates content from UK Food Hygiene Rating Scheme (FHRS) API V2 to Drupal entities created by <a href="/admin/help/fsa_ratings">FSA Ratings module</a>') . '</p>';
      $output .= '<p>' . t('The module has two migration configurations.') . '</p>';
      $output .= '<ul>';
      $output .= '<li>' . t('<strong>fsa_authority</strong> for importing FHRS Authorities from <code><a href="http://api.ratings.food.gov.uk/Help/Api/GET-Authorities">GET Authorities</a></code>') . '</li>';
      $output .= '<li>' . t('<strong>fsa_establishment</strong> for importing FHRS Establishments from <code><a href="http://api.ratings.food.gov.uk/Help/Api/GET-Establishments-id">GET Establishments</a></code>') . '</li>';
      $output .= '</ul>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('Import (migrate) the data using <code>drush migrate_tools</code> commands') . '</p>';
      $output .= '<ul>';
      $output .= '<li>' . t('Import Authorities: <code>drush mi --tag=authorities</code>') . '</li>';
      $output .= '<li>' . t('Import Establishments: <code>drush mi --tag=establishments</code>') . '</li>';
      $output .= '</ul>';
      $output .= '<p>' . t('<strong>NB!</strong> Authorities should be imported before Establishments') . '</p>';
      $output .= '<p>' . t('<a href="http://api.ratings.food.gov.uk">Read more about FHRS API</a>') . '</p>';
      return $output;

    default:
  }
}
