<?php

/**
 * @file
 * Custom 40x page functionalities.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\block\Entity\Block;
use Drupal\Core\Access\AccessResult;

/**
 * Implements block_access().
 */
function fsa_40x_block_access(Block $block, $operation, AccountInterface $account) {

  // Be sure breadcrumbbs and page titles are not shown on error pages.
  if (in_array($block->id(), ['breadcrumbs', 'pagetitle', 'pagetitle_hero'])) {
    $routematch = \Drupal::routeMatch();
    $routename = $routematch->getRouteName();
    // Enter routes when to remove the page title in hero area.
    $routes = [
      'fsa_signin.user_registration_thank_you',
      'system.401',
      'system.403',
      'system.404',
    ];

    if (in_array($routename, $routes) || $routematch->getParameter('fsa_establishment')) {
      return AccessResult::forbidden()
        ->addCacheableDependency($block);
    }
  }
}

/**
 * Implements hook_theme().
 */
function fsa_40x_theme() {
  return [
    'fsa_40x_response' => [
      'variables' => [
        'status_code' => NULL,
        'error' => NULL,
        'content' => NULL,
      ],
    ],
  ];
}
