<?php

/**
 * @file
 * Includes FSA Lander custom functionality.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\file\Entity\File;

/**
 * Implements hook_form_node_page_form_alter().
 */
function fsa_lander_form_node_lander_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Unset promo block paragraph reference on initial node creaion.
  unset($form['field_promo_block']['widget'][0]);
}

/**
 * Implements hook_preprocess_paragraph().
 */
function fsa_lander_preprocess_field(&$variables) {

  // Define the fields to move the media image url as background to the element.
  $img_to_bg = [
    'field_content_promo',
    'field_large_promo',
  ];
  if (in_array($variables['field_name'], $img_to_bg)) {
    $i = 0;
    foreach ($variables['items'] as $item) {
      if (isset($variables['items'][$i]['content']['field_media_library_image'][0]['#media']->field_image)) {
        $fid = $variables['items'][$i]['content']['field_media_library_image'][0]['#media']->field_image->getValue()[0]['target_id'];
        $file = File::load($fid);
        $uri = $file->getFileUri();
        $variables['items'][$i]['attributes']['style'] = ['background: url(' . file_create_url($uri) . ')'];

        // And unset the element, no matter how it is in configured in display.
        unset($variables['items'][$i]['content']['field_media_library_image']);
      }
      $i++;
    }
  }

  // Add properties and attributes for lander rows.
  if ($variables['field_name'] == 'field_lander_row') {
    $i = 0;
    foreach ($variables['items'] as $item) {

      if (isset($item['content']['#paragraph'])) {

        // Customize different paragraph types.
        switch ($item['content']['#paragraph']->getType()) {
          case 'code_block':
            // Hide title if set so on edit mode.
            if ($item['content']['#paragraph']->field_hide_title->value) {
              // @todo: catch the value and hide block title.
            }
            break;
        }
      }
      $i++;
    }
  }
}
