<?php

/**
 * @file
 * Contains fsa_surveys.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function fsa_survey_preprocess_page(&$variables) {
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    switch ($language) {
      case 'en':
        $variables['#attached']['library'][] =  'fsa_survey/survey_en';
        break;

      case 'cy':
        $variables['#attached']['library'][] =  'fsa_survey/survey_cy';
        break;
    }
  }
}