<?php

/**
 * @file
 * String overrides.
 */

/**
 * Drupal core string overrides for FSA setup.
 */
$settings['locale_custom_strings_en'][''] = [
  'You have just used your one-time login link. It is no longer necessary to use this link to log in. Please change your password.' => 'You have just used your one-time login link. Please set yourself a password that you can use to log in again.',
  'The email address %mail is not valid.', 'Please provide this information in the correct format',
];
