<?php

/**
 * @file
 * Contains fsa_topic_listing.module.
 */

use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_page_title().
 */
function fsa_topic_listing_preprocess_page_title(&$variables) {

  $route = \Drupal::routeMatch();
  $routename = $route->getRouteName();

  // Add "Show topics A-Z" listing page link after the page title.
  if ($routename == 'entity.taxonomy_term.canonical') {
    $url = Url::fromRoute('view.a_to_z.page_1');
    $url->setOptions(['attributes' => ['class' => 'button']]);
    $link = Link::fromTextAndUrl(t('Show topics A-Z'), $url)->toString();

    $variables['title_suffix'] = ['#markup' => '<div class="cta">' . $link . '</div>'];
  }

}
