<?php

/**
 * @file
 * Library functions and hook implementations for FSA Multi page Guide module.
 */

use Symfony\Component\HttpFoundation\RedirectResponse;
use \Drupal\fsa_multipage_guide\FSAMultiPageGuide;

/**
 * Implements hook_entity_view().
 *
 * If you try and look at a multi page guide you get redirected to its first page.
 */
function fsa_multipage_guide_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode === 'full' && FSAMultiPageGuide::IsGuide($entity)) {
    $guide = FSAMultiPageGuide::Get($entity);

    $first_page = $guide->getFirstPage();

    if (!empty($first_page)) {
      $response = new RedirectResponse('/node/' . $first_page->id());
      $request = \Drupal::request();
      // Save the session so things like messages get saved.
      $request->getSession()->save();
      $response->prepare($request);
      // Make sure to trigger kernel events.
      \Drupal::service('kernel')->terminate($request, $response);
      $response->send();
    }
  }
}
