<?php

/**
 * @file
 * Library functions and hook implementations for FSA Multi page Guide module.
 */

use Symfony\Component\HttpFoundation\RedirectResponse;
use \Drupal\fsa_multipage_guide\FSAMultiPageGuide;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_view().
 *
 * If you try and look at a multi page guide you get redirected to its first page.
 */
function fsa_multipage_guide_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode === 'full' && FSAMultiPageGuide::IsGuide($entity)) {
    $parameters = \Drupal::routeMatch()->getParameters();

    if ($parameters->has('export_type')) {
      // PDF export in progress, do not redirect.
      return;
    }

    $guide = FSAMultiPageGuide::Get($entity);

    $first_page = $guide->getFirstPage();

    if (!empty($first_page)) {
      $lang_code = \Drupal::languageManager()->getCurrentLanguage()->getId();

      $redirect_url = '/node/' . $first_page->id();
      if ($lang_code !== 'en') {
        $redirect_url = '/' . $lang_code . $redirect_url;
      }

      $response = new RedirectResponse($redirect_url);
      $request = \Drupal::request();
      // Save the session so things like messages get saved.
      $request->getSession()->save();
      $response->prepare($request);
      // Make sure to trigger kernel events.
      \Drupal::service('kernel')->terminate($request, $response);
      $response->send();
    }
  }
}

/**
 * Implements hook_preprocess_field_node_title().
 */
function fsa_multipage_guide_preprocess_field__node__title(&$variables) {
  if (!empty($variables['element']['#object'])) {
    $guide = FSAMultiPageGuide::GetGuideForPage($variables['element']['#object']);
    if (!empty($guide)) {
      // Give the node title an extra class if its in a guide.
      $variables['attributes']['class'][] = 'guide__page__title';
    }
  }
}


/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function fsa_multipage_guide_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() == 'node'  && !empty($fields['field_guide_pages'])) {
    $fields['field_guide_pages']->addConstraint('FSAPagesInGuide', []);
  }
}
