<?php

/**
 * @file
 * Adds custom webform validation.
 *
 * @see https://www.drupal.org/docs/8/modules/webform/webform-cookbook/how-to-add-custom-validation-to-a-webform-element
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_element_alter().
 */
function fsa_webform_validation_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  $form_ids = [
    'foreign_object--fsa_establishment_postal_code',
    'poor_hygiene_practices--fsa_establishment_postal_code',
    'food_poisoning--fsa_establishment_postal_code',
  ];
  if (isset($element['#webform_id']) && in_array($element['#webform_id'], $form_ids)) {
    $element['#element_validate'][] = [
      'Drupal\fsa_webform_validation\Validate\FsaWebformValidationValidate',
      'validate',
    ];
  }
}

/**
 * Implements hook_form_alter().
 */
function fsa_webform_validation_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Alter confirmation message.
  $webform_ids = [
    'foreign_object',
    'poor_hygiene_practices',
    'food_poisoning',
  ];
  if (isset($form['#webform_id']) && in_array($form['#webform_id'], $webform_ids)) {
    if (isset($form['confirmation'])) {
      if (empty($form_state->getValue('fsa_establishment_la_name')) || empty($form_state->getValue('fsa_establishment_la_name'))) {
        if ($form['confirmation']['#webform']->getSetting('confirmation_message')) {
          $value = t('<h2>Report complete</h2>');
          $value .= t('<p>Thank you for your report. It has been forwarded to the relevant Local Authority.</p>');
          $form['confirmation']['#webform']->setSetting('confirmation_message', $value);
        }
      }
    }
    if (isset($form['preview'])) {
      if ($form_state->getValue('fsa_establishment_la_name')) {
        $name = t('@name Council', [
          '@name' => $form_state->getValue('fsa_establishment_la_name'),
        ]);
        $form['elements']['#markup'] = t('Your report will be sent to @la to investigate.', [
          '@la' => $name,
        ]);
      }
    }
  }
}
